services:
  android:
    build: ./android/
    env_file: ./android/.env
    ports:
      - "19000:19000"
    tty: true
    volumes:
      - .:/home/bouzuya/kireta
  firebase:
    build: ./firebase/
    tty: true
    volumes:
      - ./firebase:/firebase
  rust:
    build: ./rust/
    env_file: ./rust/.env
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./rust:/rust
