services:
  android:
    build: ./android/
    env_file: ./android/.env
    ports:
      - "19000:19000"
    tty: true
    volumes:
      - .:/home/node
  firebase:
    build: ./firebase/
    tty: true
    volumes:
      - ./firebase:/firebase
